definitions:
  steps:
    - step: &init-fmt
        name: 1 - Initialize, Format, and Validate Terraform
        image: hashicorp/terraform
        script:
          - terraform fmt -recursive

    - step: &deploy-to-tst
        name: 2 - Test
        image: hashicorp/terraform
        deployment: Test
        trigger: manual
        script:
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_TEST
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TEST
          - terraform -chdir="infra/terraform/main" init -backend-config ../../terraform/environments/test/backend.conf -backend-config="access_key=$AWS_ACCESS_KEY_ID -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY -backend-config="region=us-east-1" -reconfigure
          - terraform -chdir="infra/terraform/main" plan -var-file='../../terraform/environments/test/variables.tfvars'
          - terraform -chdir="infra/terraform/main" apply -auto-approve -var-file='../../terraform/environments/test/variables.tfvars'

    - step: &deploy-to-stg
        name: 3 - Staging
        image: hashicorp/terraform
        deployment: Staging
        trigger: manual
        script:
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STAGING
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STAGING
          - terraform -chdir="infra/terraform/main" init -backend-config ../../terraform/environments/staging/backend.conf -backend-config="access_key=$AWS_ACCESS_KEY_ID -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY -backend-config="region=us-east-1" -reconfigure
          - terraform -chdir="infra/terraform/main" plan -var-file='../../terraform/environments/staging/variables.tfvars'
          - terraform -chdir="infra/terraform/main" apply -auto-approve -var-file='../../terraform/environments/staging/variables.tfvars'

    - step: &deploy-to-prd
        name: 4 - Production
        image: hashicorp/terraform
        deployment: Production
        trigger: manual
        script:
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
          - terraform -chdir="infra/terraform/main" init -backend-config ../../terraform/environments/prod/backend.conf -backend-config="access_key=$AWS_ACCESS_KEY_ID -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY -backend-config="region=us-east-1" -reconfigure
          - terraform -chdir="infra/terraform/main" plan -var-file='../../terraform/environments/prod/variables.tfvars'
          - terraform -chdir="infra/terraform/main" apply -auto-approve -var-file='../../terraform/environments/prod/variables.tfvars'

pipelines:
# This session decides from where the team are allowed to deploy on TST, STG or PRD
# In our case only from the main branch is possible to deploy on PRD
  branches:
    chl-*:
     - step: *init-fmt
     - step: *deploy-to-tst
     - step: *deploy-to-stg
    main:
      - step: *init-fmt
      - step: *deploy-to-tst
      - step: *deploy-to-stg
      - step: *deploy-to-prd